// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	repository "leal.co/orders/internal/domain/repository"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCity provides a mock function with given fields: _a0
func (_m *Repository) GetCity(_a0 int) repository.CityDTO {
	ret := _m.Called(_a0)

	var r0 repository.CityDTO
	if rf, ok := ret.Get(0).(func(int) repository.CityDTO); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(repository.CityDTO)
	}

	return r0
}

// GetClient provides a mock function with given fields: _a0
func (_m *Repository) GetClient(_a0 int) repository.ClientDTO {
	ret := _m.Called(_a0)

	var r0 repository.ClientDTO
	if rf, ok := ret.Get(0).(func(int) repository.ClientDTO); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(repository.ClientDTO)
	}

	return r0
}

// SaveOrder provides a mock function with given fields: _a0
func (_m *Repository) SaveOrder(_a0 repository.NewOrderDTO) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(repository.NewOrderDTO) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
